[package]
name = "migrations_internals"
version = "2.0.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Internal implementation of diesels migration mechanism"
homepage = "https://diesel.rs"

[dependencies]
serde = {version = "1", features = ["derive"]}
toml = "0.5"

